### ISSUE TITLE
ZipArchive::close() Error

### ISSUE THREAD

**Issue by 2braincells2go** [abdulawal39/ZipCF#1]
Hi. Having issue and tried on two different servers.

Here is the error:

`Warning: ZipArchive::close(): Read error: Is a directory in /home/mathtest/public_html/testbed/zipCF.php on line 105
Failed to create zip file, Please try again`

Have had no other zip issues so fairly certain all zip extensions are active.

Any ideas on issue?

Thanks much.

Woody

**Comment by abdulawal39** [comment]
Hi 2braincells2go,
Sorry for so late response. It should work fine now with the latest commit.

Thank You

**Comment by 2braincells2go** [comment]
Thank you and sorry for the late reply @abdulawal39 

I will give new version a try and report back here if any issues.

Closing
